name: .NET

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    outputs:
      code_changed: ${{ steps.set_outputs.outputs.code_changed }}
      docs_changed: ${{ steps.set_outputs.outputs.docs_changed }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0         # 모든 커밋을 fetch

      - name: Filter code & docs changes
        if: github.event_name == 'push'
        id: filter
        uses: dorny/paths-filter@v2
        continue-on-error: true
        with:
          filters: |
            code:
              - '**/*.cs'
              - '**/*.sln'
              - '**/*.csproj'
            docs:
              - 'README.md'
              - 'LICENSE'
          token: ''               # 빈 문자열로 설정하면 git diff fallback
          list-files: 'none'      # 파일 목록 생략, true/false 출력
          initial-fetch-depth: 0  # 로컬 git diff로 충분히 감지

      - name: Set job outputs
        if: github.event_name == 'push'
        id: set_outputs
        run: |
          echo "code_changed=${{ steps.filter.outputs.code || 'false' }}" >> $GITHUB_OUTPUT
          echo "docs_changed=${{ steps.filter.outputs.docs || 'false' }}" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore InvenAdClicker.sln

      - name: Build
        run: dotnet build InvenAdClicker.sln --no-restore

      - name: Test
        run: dotnet test InvenAdClicker.sln --no-build --verbosity normal

  release:
    needs: build
    runs-on: windows-latest
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      (needs.build.outputs.code_changed == 'true' || needs.build.outputs.docs_changed == 'true')

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: dotnet publish InvenAdClicker.sln --no-build --output ./publish

      - name: Copy README and LICENSE into publish folder
        run: |
          copy README.md .\publish\README.md
          copy LICENSE .\publish\LICENSE

      - name: Zip Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          filename: InvenAdClicker.zip
          directory: ./publish

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./publish/InvenAdClicker.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}