name: .NET

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: windows-latest
    outputs:
      code_changed: ${{ steps.set_outputs.outputs.code_changed }}
      docs_changed: ${{ steps.set_outputs.outputs.docs_changed }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 모든 커밋을 fetch

      - name: Filter code & docs changes
        id: filter
        uses: dorny/paths-filter@v2
        continue-on-error: true
        with:
          filters: |
            code:
              - '**/*.cs'
              - '**/*.sln'
              - '**/*.csproj'
            docs:
              - 'README.md'
              - 'LICENSE'
          token: ${{ secrets.GITHUB_TOKEN }} # PR 변경 감지
          list-files: 'none' # 파일 목록 생략, true/false 출력

      - name: Set job outputs
        id: set_outputs
        run: |
          echo "code_changed=${{ steps.filter.outputs.code || 'false' }}" >> $GITHUB_OUTPUT
          echo "docs_changed=${{ steps.filter.outputs.docs || 'false' }}" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore InvenAdClicker.sln

      - name: Build
        run: dotnet build InvenAdClicker.sln --no-restore

      - name: Test
        run: dotnet test InvenAdClicker.sln --no-build --verbosity normal

  release:
    needs: build
    runs-on: windows-latest
    if: |
      (
        github.event_name == 'pull_request' &&
        github.event.action == 'closed' &&
        github.event.pull_request.merged == true &&
        github.event.pull_request.base.ref == 'main'
      )

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore InvenAdClicker.sln

      - name: Publish
        run: dotnet publish InvenAdClicker.sln --no-build --output ./publish

      - name: Copy README and LICENSE into publish folder
        run: |
          copy README.md .\publish\README.md
          copy LICENSE .\publish\LICENSE

      - name: Zip Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          filename: InvenAdClicker.zip
          directory: ./publish

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "./publish/InvenAdClicker.zip"