name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore InvenAdClicker.sln
      
    - name: Build
      run: dotnet build InvenAdClicker.sln --no-restore
      
    - name: Test
      run: dotnet test InvenAdClicker.sln --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish InvenAdClicker.sln --no-build --output ./publish
      
    - name: Zip Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        filename: InvenAdClicker.zip
        directory: ./publish
        
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./publish/InvenAdClicker.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
